package org.androidaudioplugin.ports.juce.ysfx

import android.content.Context
import android.os.Environment
import androidx.startup.Initializer
import java.io.File
import java.io.FileOutputStream

/**
 * Copies bundled JSFX content (from `assets/jsfx/<source>/...`) into a
 * user-visible Documents directory on first launch.
 *
 * The destination is the app-scoped external Documents directory, i.e.
 * `/sdcard/Android/data/<applicationId>/files/Documents/jsfx/...`. That
 * location is:
 *
 *  - browsable from the system Files app and any DocumentsProvider host
 *    (which is how a JSFX file can be opened via SAF),
 *  - writable by this app without runtime permissions (no
 *    READ/WRITE_EXTERNAL_STORAGE, no MANAGE_EXTERNAL_STORAGE),
 *  - retained for the lifetime of the install (cleared on uninstall).
 *
 * If you want the content under the truly public `/sdcard/Documents/`
 * instead, that requires either MediaStore.Files (Android 10+) or
 * MANAGE_EXTERNAL_STORAGE; the destination here is the modern
 * scoped-storage replacement.
 */
class YsfxJsfxContentInitializer : Initializer<Any?> {

    override fun create(context: Context): Any {
        val docs = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
            ?: context.filesDir // worst-case fallback when external storage is unavailable
        val target = File(docs, "jsfx")
        // Marker keeps this idempotent across launches without scanning every file each time.
        val marker = File(target, ".bundled-content-extracted")
        if (marker.exists()) return ""

        target.mkdirs()
        val sources = context.assets.list("jsfx") ?: emptyArray()
        for (sub in sources)
            xcopyFromAssets(context, File(target, sub), "jsfx/$sub")

        marker.writeText("Generated by ${javaClass.simpleName}.\nDelete this file to re-extract bundled JSFX content on next launch.\n")
        return ""
    }

    override fun dependencies(): MutableList<Class<out Initializer<*>>> = mutableListOf()

    private fun xcopyFromAssets(context: Context, dst: File, src: String) {
        val list = context.assets.list(src) ?: return
        if (list.isNotEmpty()) {
            if (!dst.exists()) dst.mkdirs()
            for (sub in list)
                xcopyFromAssets(context, File(dst, sub), "$src/$sub")
        } else {
            // Don't overwrite a file the user may have edited locally.
            if (dst.exists()) return
            FileOutputStream(dst).use { w ->
                context.assets.open(src).use { r -> r.copyTo(w) }
            }
        }
    }
}
